#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [4]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [10]:
a = np.zeros(10, dtype = np.int) 
print(a)

[0 0 0 0 0 0 0 0 0 0]


#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [7]:
help(np.add)


Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [11]:
a = np.zeros(10, dtype = np.int) 
print(a)
a[5]=1
print(a)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]


#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [13]:
a = np.arange(10,49) 
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [17]:
a = np.arange(0,50) 
print(a)
reversed_a = a[::-1] 
print(reversed_a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [25]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի ինդեքսները:

In [29]:
a = np.array([1,2,0,0,4,0])
a

array([1, 2, 0, 0, 4, 0])

In [30]:
result = np.where(a != 0)
result

(array([0, 1, 4], dtype=int64),)

#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [40]:
array =  np.arange(1, 20)
print(array)
random_matrix = np.random.randint(1, 20, (3, 3))
print(random_matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[10 11 13]
 [10 19 17]
 [ 2  5  1]]


#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [47]:
a = np.random.randint(1, 100, (10, 10))
print(a)
print(a.min())
print(a.max())

[[16 46 72 21 25 52 74 64 36 21]
 [28 33 12 25 11 77 21 46 85 25]
 [45 95 45 58 65 44 76 20 97 22]
 [83 38 14 84  9 82 51 31 41 10]
 [25 79 71 52 75 49 49 86 81 85]
 [63  7 56  8 50 29 13 50 74 52]
 [62 32 12 10 28 30 58 37  8 97]
 [87 37 29 85 84 85 41 11 97  4]
 [55 32 33 76 45 45 47 31 37 89]
 [93 32 95 35 42 44 63  9 37 83]]
4
97


#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [53]:
v = np.random.rand(30)
print(v)
print(v.mean())

[0.78145862 0.40554568 0.68667449 0.64151791 0.64039309 0.78562967
 0.83855073 0.24409593 0.88985374 0.43917635 0.91347688 0.43475328
 0.61074511 0.15171938 0.79147134 0.91320342 0.00129122 0.33186727
 0.31652591 0.52792467 0.0106336  0.9693588  0.42439621 0.30643115
 0.29440566 0.40838697 0.98567767 0.87054735 0.66006119 0.17862244]
0.548479857323258


#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [63]:
a = np.arange(0,10)
print(a)
a = a[((a>3) & (a<8))]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7]


#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [75]:
a = np.random.randint(0, 10, (1, 20))
print(a)
a_less_than_5 = a[(a<5)]
print(a_less_than_5)
print(a_less_than_5*2)

[[4 4 4 0 4 7 7 1 1 7 6 3 9 5 4 6 4 1 4 7]]
[4 4 4 0 4 1 1 3 4 4 1 4]
[8 8 8 0 8 2 2 6 8 8 2 8]


#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [74]:
a = np.array([1, 5, 6, 2, -2, 23, 45])
result = np.where(a % 2 == 0)
result

(array([2, 3, 4], dtype=int64),)

#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [76]:
a = np.arange(0,10)
print (a)
print (a[(a%3==0)])


[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]


#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [77]:
a = np.random.randint(0, 4, (5, 5))
print(a)

[[3 1 1 0 1]
 [0 1 2 1 1]
 [0 1 0 1 3]
 [2 1 1 3 3]
 [1 0 2 1 2]]


#### 17. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in the array.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի մեծագույն ու փոքրագույն արժեքները։

In [79]:
a = np.array([[0, 1],[2, 3]])
print (a.min())
print (a.max())

0
3


#### 18. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in each column.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի սյուների մեծագույն ու փոքրագույն արժեքները։

In [82]:
a = np.array([[0, 1],[2, 3]])
print(np.amin(a,1))
print(np.amin(a,0)) 

[0 2]
[0 1]


#### 19. Create  numpy array of size 10 filled with integers of your choice. Compute mean, median, standard deviation and variance of the array values. 

#### Ստեղծեք 10 չափանի numpy array, հաշվեք array-ի mean, median, standard deviation և variance։

In [86]:
a = np.arange(0,10)
print (a)
print(a.mean())
print(np.mean(a)) 
print(np.median(a))
print (np.std(a))
print (np.var(a))

[0 1 2 3 4 5 6 7 8 9]
4.5
4.5
4.5
2.8722813232690143
8.25


#### 20. Calculate the weighted average of the following array: np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5]) using weights np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]). 

#### Հաշվեք տրված array-ի կշռված միջինը՝ np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])` օգտագործելով np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) weight-երը։

In [104]:
a = np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])
wts = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print (np.average(a,weights = wts))

13.654545454545454


#### 21. Sort the rows of the following numpy array in an increasing order: np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]). 

#### Աճման կարգով դասավորեք տրված numpy array-ի տողերը՝ np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]):

In [103]:
a = np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]])
print (a)
np.sort(a, axis = 1)

[[4 2 6 1]
 [0 2 6 1]
 [4 4 1 9]]


array([[1, 2, 4, 6],
       [0, 1, 2, 6],
       [1, 4, 4, 9]])

#### 22. Create the following numpy arrays and calculate the dot product between a and b. 

#### Ստեղծեք հետևյալ numpy array-ները ու հաշվեք a և b array-ների dot product-ը։

$$a = \begin{bmatrix} 3 & 6 & 7 \\ 5 & -3 & 0  \end{bmatrix}$$

$$b = \begin{bmatrix} 1 & 1 \\ 2 & 1 \\ 3 & -3 \end{bmatrix}$$

In [93]:
a = np.array([[3,6,7],[5,-3,0]])
b = np.array([[1,1],[2,1],[3,-3]])
print(a.dot(b))


[[ 36 -12]
 [ -1   2]]
