'telecom.csv'

In [2]:
# preprocessing here
import numpy as np
import pandas as pd
df = pd.read_csv("telecom.csv")
df

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7853-GVUDZ  Female              0     Yes        Yes       1   
1     6893-ODYYE    Male              0      No         No      50   
2     0486-HECZI    Male              0     Yes         No      55   
3     8972-HJWNV  Female              1     Yes         No       7   
4     9317-WZPGV  Female              1      No         No       2   
...          ...     ...            ...     ...        ...     ...   
5995  2761-OCIAX    Male              1      No         No       2   
5996  9958-MEKUC    Male              0     Yes        Yes      72   
5997  7351-KYHQH  Female              1      No         No       7   
5998  6010-DDPPW    Male              0     Yes         No      70   
5999  4827-LTQRJ  Female              1     Yes        Yes      66   

     PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
0             Yes            No              No  No internet service  ...   
1             Yes            No     Fiber optic                  Yes  ...   
2             Yes           Yes     Fiber optic                  Yes  ...   
3             Yes           Yes     Fiber optic                   No  ...   
4             Yes            No     Fiber optic                   No  ...   
...           ...           ...             ...                  ...  ...   
5995          Yes            No     Fiber optic                   No  ...   
5996          Yes           Yes     Fiber optic                  Yes  ...   
5997          Yes            No             DSL                   No  ...   
5998          Yes           Yes              No  No internet service  ...   
5999          Yes           Yes     Fiber optic                  Yes  ...   

         DeviceProtection          TechSupport          StreamingTV  \
0     No internet service  No internet service  No internet service   
1                     Yes                  Yes                   No   
2                      No                   No                  Yes   
3                      No                   No                   No   
4                      No                   No                   No   
...                   ...                  ...                  ...   
5995                   No                   No                   No   
5996                  Yes                  Yes                   No   
5997                  Yes                   No                  Yes   
5998  No internet service  No internet service  No internet service   
5999                   No                  Yes                  Yes   

          StreamingMovies        Contract PaperlessBilling  \
0     No internet service  Month-to-month              Yes   
1                      No        One year              Yes   
2                      No  Month-to-month              Yes   
3                     Yes  Month-to-month              Yes   
4                     Yes  Month-to-month              Yes   
...                   ...             ...              ...   
5995                   No  Month-to-month              Yes   
5996                  Yes        Two year               No   
5997                   No  Month-to-month              Yes   
5998  No internet service        Two year               No   
5999                  Yes        One year              Yes   

                  PaymentMethod MonthlyCharges  TotalCharges Churn  
0       Credit card (automatic)          20.15         20.15   Yes  
1       Credit card (automatic)          90.10       4549.45    No  
2              Electronic check          96.75        5238.9   Yes  
3              Electronic check          84.55        646.85   Yes  
4     Bank transfer (automatic)          79.75         159.4   Yes  
...                         ...            ...           ...   ...  
5995           Electronic check          74.70         165.4   Yes  
5996    Credit card (automatic)         103.95        7517.7    No  
5997           Electr

In [3]:
column_names = df.columns
print(column_names)

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')


In [24]:
#Need to see how much data df contains:
print("\n")
print(df.shape)

#This method is used to get a summary of numeric values in your dataset. 
#It calculates the mean, standard deviation, minimum value, maximum value, 1st percentile, 2nd percentile, 
#3rd percentile of the columns with numeric values. It also counts the number of variables in the dataset. 
#So, we will be able to see if there are missing values in columns.
df.describe().transpose()



(6000, 21)


count         mean          std    min      25%       50%  \
customerID        6000.0  2999.500000  1732.195139   0.00  1499.75  2999.500   
gender            6000.0     0.503667     0.500028   0.00     0.00     1.000   
SeniorCitizen     6000.0     0.164167     0.370458   0.00     0.00     0.000   
Partner           6000.0     0.481500     0.499699   0.00     0.00     0.000   
Dependents        6000.0     0.300667     0.458586   0.00     0.00     0.000   
tenure            6000.0    32.474500    24.580963   0.00     9.00    29.000   
PhoneService      6000.0     0.903167     0.295755   0.00     1.00     1.000   
MultipleLines     6000.0     0.940500     0.948565   0.00     0.00     1.000   
InternetService   6000.0     1.225667     0.777716   0.00     1.00     1.000   
OnlineSecurity    6000.0     0.795667     0.862190   0.00     0.00     1.000   
OnlineBackup      6000.0     0.913000     0.881794   0.00     0.00     1.000   
DeviceProtection  6000.0     0.904333     0.880896   0.00     0.00     1.000   
TechSupport       6000.0     0.800667     0.863360   0.00     0.00     1.000   
StreamingTV       6000.0     0.991333     0.886034   0.00     0.00     1.000   
StreamingMovies   6000.0     0.990667     0.886027   0.00     0.00     1.000   
Contract          6000.0     1.308167     0.835454   0.00     1.00     2.000   
PaperlessBilling  6000.0     0.593000     0.491316   0.00     0.00     1.000   
PaymentMethod     6000.0     1.569500     1.065532   0.00     1.00     2.000   
MonthlyCharges    6000.0    64.926142    30.043373  18.25    35.80    70.525   
TotalCharges      6000.0  2810.863333  1623.804662   0.00  1402.75  2804.500   
Churn             6000.0     0.263833     0.440747   0.00     0.00     0.000   

                      75%      max  
customerID        4499.25  5999.00  
gender               1.00     1.00  
SeniorCitizen        0.00     1.00  
Partner              1.00     1.00  
Dependents           1.00     1.00  
tenure              56.00    72.00  
PhoneService         1.00     1.00  
MultipleLines        2.00     2.00  
InternetService      2.00     2.00  
OnlineSecurity       2.00     2.00  
OnlineBackup         2.00     2.00  
DeviceProtection     2.00     2.00  
TechSupport          2.00     2.00  
StreamingTV          2.00     2.00  
StreamingMovies      2.00     2.00  
Contract             2.00     2.00  
PaperlessBilling     1.00     1.00  
PaymentMethod        2.00     3.00  
MonthlyCharges      89.80   118.75  
TotalCharges      4221.25  5621.00  
Churn                1.00     1.00

In [26]:
#Need to discover the different data types df contains
#This method prints information about a DataFrame including the index dtype and column dtypes, non-null values and memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        6000 non-null   int64  
 1   gender            6000 non-null   int64  
 2   SeniorCitizen     6000 non-null   int64  
 3   Partner           6000 non-null   int64  
 4   Dependents        6000 non-null   int64  
 5   tenure            6000 non-null   int64  
 6   PhoneService      6000 non-null   int64  
 7   MultipleLines     6000 non-null   int64  
 8   InternetService   6000 non-null   int64  
 9   OnlineSecurity    6000 non-null   int64  
 10  OnlineBackup      6000 non-null   int64  
 11  DeviceProtection  6000 non-null   int64  
 12  TechSupport       6000 non-null   int64  
 13  StreamingTV       6000 non-null   int64  
 14  StreamingMovies   6000 non-null   int64  
 15  Contract          6000 non-null   int64  
 16  PaperlessBilling  6000 non-null   int64  


In [7]:
#by typing this, we can see the counts of unique numbers in each column
df.nunique()

customerID          6000
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1519
TotalCharges        5622
Churn                  2
dtype: int64

In [31]:
#Need to count of the null values of all columns in a dataframe
# Making a list of missing value types
missing_values = ["n/a", "na", "--", "-"]
df = pd.read_csv("telecom.csv", na_values = missing_values)

df.isnull().sum()*100/df.shape[0]


customerID          0.0
gender              0.0
SeniorCitizen       0.0
Partner             0.0
Dependents          0.0
tenure              0.0
PhoneService        0.0
MultipleLines       0.0
InternetService     0.0
OnlineSecurity      0.0
OnlineBackup        0.0
DeviceProtection    0.0
TechSupport         0.0
StreamingTV         0.0
StreamingMovies     0.0
Contract            0.0
PaperlessBilling    0.0
PaymentMethod       0.0
MonthlyCharges      0.0
TotalCharges        0.0
Churn               0.0
dtype: float64

In [29]:
# Total number of missing values
print("Total number of missing values:")
df.isnull().sum().sum()

Total number of missing values:


0

In [11]:
def handle_non_numerical_data(df):
    columns = df.columns.values
    for column in columns:
        text_digit_vals = {}
        def convert_to_int(val):
            return text_digit_vals[val]

        if df[column].dtype != np.int64 and df[column].dtype != np.float64:
            column_contents = df[column].values.tolist()
            unique_elements = set(column_contents)
            x = 0
            for unique in unique_elements:
                if unique not in text_digit_vals:
                    text_digit_vals[unique] = x
                    x+=1

            df[column] = list(map(convert_to_int, df[column]))

    return df

In [12]:
new_df = handle_non_numerical_data(df)
new_df

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0           1728       0              0        1           1       1   
1           4979       1              0        0           0      50   
2           1953       1              0        1           0      55   
3            300       0              1        1           0       7   
4           3518       0              1        0           0       2   
...          ...     ...            ...      ...         ...     ...   
5995        5398       1              1        0           0       2   
5996        2874       1              0        1           1      72   
5997        1137       0              1        0           0       7   
5998        4445       1              0        1           0      70   
5999        3489       0              1        1           1      66   

      PhoneService  MultipleLines  InternetService  OnlineSecurity  ...  \
0                1              0                0               1  ...   
1                1              0                2               2  ...   
2                1              2                2               2  ...   
3                1              2                2               0  ...   
4                1              0                2               0  ...   
...            ...            ...              ...             ...  ...   
5995             1              0                2               0  ...   
5996             1              2                2               2  ...   
5997             1              0                1               0  ...   
5998             1              2                0               1  ...   
5999             1              2                2               2  ...   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                    1            1            1                1         2   
1                    2            2            0                0         1   
2                    0            0            2                0         2   
3                    0            0            0                2         2   
4                    0            0            0                2         2   
...                ...          ...          ...              ...       ...   
5995                 0            0            0                0         2   
5996                 2            2            0                2         0   
5997                 2            0            2                0         2   
5998                 1            1            1                1         0   
5999                 0            2            2                2         1   

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                    1              0           20.15          3341      1  
1                    1              0           90.10          1708      0  
2                    1              2           96.75          3373      1  
3                    1              2           84.55           593      1  
4                    1              1           79.75          2640      1  
...                ...            ...             ...           ...    ...  
5995                 1              2           74.70          1005      1  
5996                 0              0          103.95          2682      0  
5997                 1              2           64.95           793      0  
5998                 0              1           25.15          4195      0  
5999                 1              0          110.60           271      0  

[6000 rows x 21 columns]

Split data into 2 parts, take the small one as the final test. You will be using for each model's final evaluation

In [14]:
# your code here
df_first_half = new_df[:5000]
df_first_half.shape

(5000, 21)

In [15]:
df_second_half = new_df[5000:]
df_second_half.shape

(1000, 21)

# Build 5 classification models

logistic regression, decision tree, random forest, knn, svm

#### tips
<br>
1. use cross validation
<br>
2. use same splits for all classifiers (to have correct comparison)
<br>
3. build a table to show statistics for all classifiers (at least - accuracy, precision and recall. Any more component would be a +)

In [16]:
# your code here

In [71]:
#Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import model_selection
from sklearn.metrics import confusion_matrix
from sklearn. preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import  precision_score, \
    recall_score, confusion_matrix, classification_report, \
    accuracy_score, f1_score

In [72]:
X = df_first_half.drop('Churn', axis=1).values 
Y = df_first_half['Churn'].values
print(X)
print(Y)

[[1.728e+03 0.000e+00 0.000e+00 ... 0.000e+00 2.015e+01 3.341e+03]
 [4.979e+03 1.000e+00 0.000e+00 ... 0.000e+00 9.010e+01 1.708e+03]
 [1.953e+03 1.000e+00 0.000e+00 ... 2.000e+00 9.675e+01 3.373e+03]
 ...
 [5.319e+03 1.000e+00 0.000e+00 ... 0.000e+00 2.530e+01 2.465e+03]
 [2.224e+03 1.000e+00 0.000e+00 ... 2.000e+00 7.050e+01 5.074e+03]
 [4.223e+03 0.000e+00 0.000e+00 ... 1.000e+00 9.490e+01 4.629e+03]]
[1 0 1 ... 0 0 0]


In [73]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.15, random_state = 0, stratify = Y)

In [74]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [75]:
#Defining the machine learning models
model1 = LogisticRegression()
model2 = DecisionTreeClassifier(max_depth = 2)
model3 = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)
model4 = SVC()
model5 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)

In [76]:
#Training the machine learning models
model1.fit(X_train, Y_train)
model2.fit(X_train, Y_train)
model3.fit(X_train, Y_train)
model4.fit(X_train, Y_train)
model5.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [77]:
#Making the prediction
Y_pred1 = model1.predict(X_test)
Y_pred2 = model2.predict(X_test)
Y_pred3 = model3.predict(X_test)
Y_pred4 = model4.predict(X_test)
Y_pred5 = model5.predict(X_test)

In [78]:
#Confusion matrix
cm_LogisticRegression = confusion_matrix(Y_test, Y_pred1)
cm_DecisionTree = confusion_matrix(Y_test, Y_pred2)
cm_RandomForest = confusion_matrix(Y_test, Y_pred3)
cm_SupportVectorClass = confusion_matrix(Y_test, Y_pred4)
cm_KNN = confusion_matrix(Y_test, Y_pred5)

In [79]:
#10-fold cross-validation 
kfold = model_selection.KFold(n_splits=10, random_state = 0)
result1 = model_selection.cross_val_score(model1, X_train, Y_train, cv=kfold)
result2 = model_selection.cross_val_score(model2, X_train, Y_train, cv=kfold)
result3 = model_selection.cross_val_score(model3, X_train, Y_train, cv=kfold)
result4 = model_selection.cross_val_score(model4, X_train, Y_train, cv=kfold)
result5 = model_selection.cross_val_score(model5, X_train, Y_train, cv=kfold)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


In [80]:
#Printing the accuracies achieved in cross-validation
print('Accuracy of Logistic Regression Model = ',result1.mean())
print('Accuracy of Decision Tree Model = ',result2.mean())
print('Accuracy of Random Forest Model = ',result3.mean())
print('Accuracy of Support Vector Machine = ',result4.mean())
print('Accuracy of k-NN Model = ',result5.mean())

Accuracy of Logistic Regression Model =  0.8030588235294118
Accuracy of Decision Tree Model =  0.7623529411764707
Accuracy of Random Forest Model =  0.7642352941176471
Accuracy of Support Vector Machine =  0.7995294117647058
Accuracy of k-NN Model =  0.7621176470588236


In [95]:
#scoring parameter: accuracy_score
from sklearn.metrics import accuracy_score
print('Accuracy score of Logistic Regression Model:') 
print(accuracy_score(Y_test, Y_pred1))
print('Accuracy score of Decision Tree Model: ')
print(accuracy_score(Y_test, Y_pred2))
print('Accuracy score of Random Forest Model:')
print(accuracy_score(Y_test, Y_pred3))
print('Accuracy score of Support Vector Machine:')
print(accuracy_score(Y_test, Y_pred4))
print('Accuracy score of k-NN Model:')
print(accuracy_score(Y_test, Y_pred5))

Accuracy score of Logistic Regression Model:
0.804
Accuracy score of Decision Tree Model: 
0.7733333333333333
Accuracy score of Random Forest Model:
0.7573333333333333
Accuracy score of Support Vector Machine:
0.7906666666666666
Accuracy score of k-NN Model:
0.7586666666666667


In [109]:
#scoring parameter: recall_score
#When true positive + false negative == 0, recall returns 0 and raises UndefinedMetricWarning. 
#This behavior can be modified with zero_division.
from sklearn.metrics import recall_score
print('Recall score of Logistic Regression Model:') 
print(recall_score(Y_test, Y_pred1, average=None, zero_division=1))
print('Recall score of Decision Tree Model: ')
print(recall_score(Y_test, Y_pred2, average=None, zero_division=1))
print('Recall score of Random Forest Model:')
print(recall_score(Y_test, Y_pred3, average=None, zero_division=1))
print('Recall score of Support Vector Machine:')
print(recall_score(Y_test, Y_pred4, average=None, zero_division=1))
print('Recall score of k-NN Model:')
print(recall_score(Y_test, Y_pred5, average=None, zero_division=1))

Recall score of Logistic Regression Model:
[0.8972973  0.53846154]
Recall score of Decision Tree Model: 
[0.81441441 0.65641026]
Recall score of Random Forest Model:
[0.98378378 0.11282051]
Recall score of Support Vector Machine:
[0.90810811 0.45641026]
Recall score of k-NN Model:
[0.83603604 0.53846154]


In [107]:
from sklearn.metrics import precision_score
print('Precision score of Logistic Regression Model:') 
print(precision_score(Y_test, Y_pred1, average=None, zero_division=1))
print('Precision score of Decision Tree Model: ')
print(precision_score(Y_test, Y_pred2, average=None, zero_division=1))
print('Precision score of Random Forest Model:')
print(precision_score(Y_test, Y_pred3, average=None, zero_division=1))
print('Precision score of Support Vector Machine:')
print(precision_score(Y_test, Y_pred4, average=None, zero_division=1))
print('Precision score of of k-NN Model:')
print(precision_score(Y_test, Y_pred5, average=None, zero_division=1))

Precision score of Logistic Regression Model:
[0.84693878 0.64814815]
Precision score of Decision Tree Model: 
[0.87090559 0.55411255]
Precision score of Random Forest Model:
[0.75938804 0.70967742]
Precision score of Support Vector Machine:
[0.82622951 0.63571429]
Precision score of of k-NN Model:
[0.83754513 0.53571429]


In [96]:
#scoring parameter: average_precision_score
from sklearn.metrics import average_precision_score
print('Average precision score of Logistic Regression Model:') 
print(average_precision_score(Y_test, Y_pred1))
print('Average precision score of Decision Tree Model: ')
print(average_precision_score(Y_test, Y_pred2))
print('Average precision score of Random Forest Model:')
print(average_precision_score(Y_test, Y_pred3))
print('Average precision score of Support Vector Machine:')
print(average_precision_score(Y_test, Y_pred4))
print('Average precision score of k-NN Model:')
print(average_precision_score(Y_test, Y_pred5))

Average precision score of Logistic Regression Model:
0.469002849002849
Average precision score of Decision Tree Model: 
0.45305849705849705
Average precision score of Random Forest Model:
0.3107328370554177
Average precision score of Support Vector Machine:
0.4314798534798535
Average precision score of k-NN Model:
0.40846153846153843


In [112]:
data = [["Regression Model", 0.803, 0.804, 0.897, 0.847, 0.469], 
       ["Decision Tree Model", 0.762, 0.773, 0.814, 0.870, 0.453], 
       ["Random Forest Model",0.764, 0.757, 0.984,0.759, 0.311],
       ["Support Vector Machine", 0.799, 0.791, 0.908, 0.826, 0.431],
       ["k-NN Model", 0.762, 0.759, 0.836, 0.837, 0.408]]
pd.DataFrame(data, columns=["Model name", "Accuracies achieved in cross-validation", "Accuracy score", "Recall score", "Precision score", "Average precision score"])

Model name  Accuracies achieved in cross-validation  \
0        Regression Model                                    0.803   
1     Decision Tree Model                                    0.762   
2     Random Forest Model                                    0.764   
3  Support Vector Machine                                    0.799   
4              k-NN Model                                    0.762   

   Accuracy score  Recall scor  Precision score  Average precision score  
0           0.804        0.897            0.847                    0.469  
1           0.773        0.814            0.870                    0.453  
2           0.757        0.984            0.759                    0.311  
3           0.791        0.908            0.826                    0.431  
4           0.759        0.836            0.837                    0.408

In [ ]:
#not working!!!!
PTable
from prettytable import PrettyTable
    
x = PrettyTable()

x.field_names = ["Model name", "Accuracies achieved in cross-validation", "Accuracy score", "Recall scor", "Precision score", "Average precision score"]

x.add_row(["Regression Model", 0.803, 0.804, 0.897, 0.847, 0.469])
x.add_row(["Decision Tree Model", 0.762, 0.773, 0.814, 0.870, 0.453])
x.add_row(["Random Forest Model",0.764, 0.757, 0.984, 0.311])
x.add_row(["Support Vector Machine", 0.799, 0.791, 0.908, 0.826, 0.431])
x.add_row(["k-NN Model", 0.762, 0.759, 0.836, 0.837, 0.408])

print(x)



In [ ]:
#not working!!!!
print("Report:",  "\n", metrics.classification_report(X_train, Y_pred1))

#### choose the best model. Either retrain it or copy it in the cell below

In [116]:
# final_model = ...().fit(...) # example for retraining

#The precision is intuitively the ability of the classifier not to label as positive a sample that is negative.
#The recall is intuitively the ability of the classifier to find all the positive samples.
#So I decided that Logistic Regression Model is the more suitable one.

X_f = df_second_half.drop('Churn', axis=1).values 
Y_f = df_second_half['Churn'].values
X_f_train, X_f_test, Y_f_train, Y_f_test = train_test_split(X_f, Y_f, test_size = 0.15, random_state = 0, stratify = Y_f)
sc = StandardScaler()
X_f_train = sc.fit_transform(X_f_train)
X_f_test = sc.transform(X_f_test)
final_model = LogisticRegression()
final_model.fit(X_f_train, Y_f_train)
Y_pred_final = final_model.predict(X_f_test)
print('Accuracy score of Logistic Regression Model - final results:') 
print(accuracy_score(Y_f_test, Y_pred_final))
print('Recall score of Logistic Regression Model:') 
print(recall_score(Y_f_test, Y_pred_final, average=None, zero_division=1))
print('Precision score of Logistic Regression Model:') 
print(precision_score(Y_f_test, Y_pred_final, average=None, zero_division=1))

Accuracy score of Logistic Regression Model - final results:
0.8
Recall score of Logistic Regression Model:
[0.90654206 0.53488372]
Precision score of Logistic Regression Model:
[0.82905983 0.6969697 ]
